language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
    - mongodb
before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379
script:
  - npm ci
  - npm test
after_success: 
  - npm run coveralls
