version: "3"
services:
  webapp:
    build: .
    environment:
      PORT: 9000
    command: ./node_modules/nodemon/bin/nodemon.js --exec babel-node app.js
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - mongodb
      - redis
    ports:
      - "9000:9000"
  mongodb:
    image: mongo:4.0-xenial
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:12000"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  mongodb-data:
  redis-data:
